require('./transfer_wqt.js');
require('./update_arbiter.js');
require('./check_arbiter.js');
require('./add_token_to_bridge.js');
require('./set_bridge_to_wqt.js');
require('./set_bridge_to_wrapped.js');
require('./set_dao_as_admin.js');
require('./exchange_wqt.js');
require('./check_bridge_tokens.js');